version: '2'
services:
  skript-mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "example"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: "nette"
      ADMINER_PLUGINS: "edit-calendar"
    ports:
      - 127.0.0.1:8080:8080

