version: '2'
services:
  skript-mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "example"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 127.0.0.1:3603:3603
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080

