# Generated by Django 2.1.2 on 2018-10-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studserviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='tip_nastave',
            field=models.CharField(max_length=30),
        ),
    ]
