# Generated by Django 2.1.2 on 2018-12-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studserviceapp', '0002_auto_20181027_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='izborgrupe',
            name='izabrana_grupa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='studserviceapp.IzbornaGrupa'),
        ),
        migrations.AddField(
            model_name='student',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='djangouploads'),
        ),
        migrations.AlterField(
            model_name='obavestenje',
            name='fajl',
            field=models.FileField(upload_to='djangouploads'),
        ),
        migrations.AlterField(
            model_name='rasporednastave',
            name='datum_unosa',
            field=models.DateTimeField(null=True),
        ),
    ]
